CREATE DATABASE [VENDAS SUCOS];

CREATE DATABASE [VENDAS SUCOS 2]
ON (
	NAME='VENDAS_SUCOS_2_DAT',
	FILENAME='C:\TEMP\VENDAS_SUCOS_02.MDF',
	SIZE=10,
	MAXSIZE=50,
	FILEGROWTH=5
)
LOG ON (
	NAME='VENDAS_SUCOS_2_LOG',
	FILENAME='C:\TEMP\VENDAS_SUCOS_02.LDF',
	SIZE=10,
	MAXSIZE=50,
	FILEGROWTH=5
);

DROP DATABASE [VENDAS SUCOS 2];

CREATE TABLE PRODUTOS
  (
     CODIGO      VARCHAR(10) NOT NULL,
     DESCRITOR   VARCHAR(100) NULL,
     SABOR       VARCHAR(50) NULL,
     TAMANHO     VARCHAR(50) NULL,
     EMBALAGEM   VARCHAR(50) NULL,
     PRECO_LISTA FLOAT NULL,
     PRIMARY KEY (CODIGO)
  );

CREATE TABLE VENDEDORES
  (
     MATRICULA     VARCHAR(5) NOT NULL,
     NOME          VARCHAR(100) NULL,
     BAIRRO        VARCHAR(50) NULL,
     COMISSAO      FLOAT NULL,
     DATA_ADMISSAO DATE NULL,
     FERIAS        BIT NULL,
     PRIMARY KEY (MATRICULA)
  );

CREATE TABLE TABELA_DE_VENDAS
  (
     NUMERO     VARCHAR(5) NOT NULL,
     DATA_VENDA DATE NULL,
     CPF        VARCHAR(11) NOT NULL,
     MATRICULA  VARCHAR(11) NOT NULL,
     IMPOSTO    FLOAT NULL,
     PRIMARY KEY (NUMERO)
  );

ALTER TABLE TABELA_DE_VENDAS
  ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS
  ADD CONSTRAINT FK_VENDEDORES FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (
  MATRICULA);

CREATE TABLE TABELA_DE_VENDAS
  (
     NUMERO     VARCHAR(5) NOT NULL,
     DATA_VENDA DATE NULL,
     CPF        VARCHAR(11) NOT NULL,
     MATRICULA  VARCHAR(11) NOT NULL,
     IMPOSTO    FLOAT NULL,
     PRIMARY KEY (NUMERO)
  );

ALTER TABLE TABELA_DE_VENDAS
  ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS
  ADD CONSTRAINT FK_VENDEDORES FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (
  MATRICULA);

ALTER TABLE TABELA_DE_VENDAS
  ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL;

ALTER TABLE TABELA_DE_VENDAS
  ADD CONSTRAINT FK_VENDEDORES FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (
  MATRICULA);