CREATE PROCEDURE BuscaNotasCliente
DECLARE @CPF AS VARCHAR(12) = '19290992743'
DECLARE @DATA_INICIAL AS DATETIME = '20160101'
DECLARE @DATA_FINAL AS DATETIME = '20161231'
AS
BEGIN
   SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF
   AND DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL
END;